import Foundation

public struct Song {
    public let title: String
    public let songLenght: NSTimeInterval
    public let artWorkURL: String
    
    //This should be generated by the compiler...
    public init(title: String, songLenght: NSTimeInterval, artWorkURL: String) {
        self.title = title
        self.songLenght = songLenght
        self.artWorkURL = artWorkURL
    }
}

