default_platform(:ios)
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"

before_all do |lane, options|
  setup_jenkins(derived_data_path: "./derivedData")
end

platform :ios do
  desc "Execute unit tests"
  lane :unit_tests do
    run_tests(
      workspace: "BSWInterfaceKit.xcworkspace",
      scheme: "BSWInterfaceKitDemo",
      devices: ["iPhone 11"],
      )
  end
end

after_all do |lane, options|
  clear_derived_data(derived_data_path: "./derivedData")
end
