default_platform(:ios)

platform :ios do
  desc "Setup environment"
  lane :setup_environment do
    setup_jenkins(derived_data_path: "./derivedData")
  end

  desc "Teardown environment"
  lane :teardown_environment do
    clear_derived_data
  end

  desc "Execute unit tests"
  lane :unit_tests do

    xcodebuild(
      test: true,
      scheme: "BSWInterfaceKit",
      destination: "platform=iOS Simulator,name=iPhone 11,OS=14.5"
    )
  end
end


after_all do |lane, options|
  clear_derived_data(derived_data_path: "./derivedData")
end
